# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_login', '0002_auto_20190426_0547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='moblie_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
